parameters:
    edgar_ez_cdn.cdn_listener_class: EdgarEz\CDNBundle\EventListener\CDNListener

services:
    edgar_ez_cdn.cdn_listener:
        class: %edgar_ez_cdn.cdn_listener_class%
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setDomain, [$domain;edgar_ez_cdn$]]
            - [setExtensions, [$extensions;edgar_ez_cdn$]]
