parameters:
    smile_ez_cdn.cdn_listener_class: Smile\EzCDNBundle\EventListener\CDNListener

services:
    smile_ez_cdn.cdn_listener:
        class: "%smile_ez_cdn.cdn_listener_class%"
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setDomain, [$domain;smile_ez_cdn$]]
            - [setExtensions, [$extensions;smile_ez_cdn$]]
